### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by slarge** [andybeet/MS_Hydra#1]
I think it might make sense to rename the hydras to hydra_sim (for simulation code) and hydra_est (for estimation code). Would the mshydradata package support both, or will it only work with simulation code? If it works for both hydras, maybe we just simplify to hydradata. What do you think @andybeet and @sgaichas? Or, do I need to get over being pedantic about names... 😈 

Note: I'm not certain if linux/mac/ADMB has problems with underscores in names? If so, we should plan accordingly

**Comment by sgaichas** [comment]
I'm fine with hydra_sim and hydra_est; this is how I've always thought about them. If MS stands for multispecies, that is implied by the 10 headed Hydra monster. :-)
In my memory, the Linux/ADMB combo had problems with capital vs lower case in directory names, so all lower is best. underscores work but never blank spaces.

**Comment by andybeet** [comment]
i'm fine with those naming suggestions. mshydradata can of course be renamed too. There is no reason i couldn't make the mshydradata package work for both sim and est versions of Hydra. Currently it wont. When the main structure of the estimation model is complete i can tailor it.
