### ISSUE TITLE
Reallocate effort among fleets

### ISSUE THREAD

**Issue by slarge** [andybeet/MS_Hydra#4]
Since Hydra is effort driven, alternative management strategies rely on changing the effort of fishing. We need to think of ways to reallocate effort among fleets when a reference point has been breached. Currently all fleets are impacted in a similar fashion. (fishing behavioral models alternative to shared pain, ask SSB)

**Comment by andybeet** [comment]
This has been done. Functional groups have been "assigned" to a fleet based on the fleet which primarily fishes the group. Then when a groups biomass levels (or a species in a group) fall below some threshold we can change the effort of a particular fleet. https://github.com/NOAA-EDAB/hydra_sim/commit/04b0c7600dd3c685be023f578f2f6520bd71d039
